site_name: antiSMASH Documentation
nav:
    - Home: index.md
    - Using antiSMASH:
      - Introduction: intro.md
      - Submitting jobs on the website: website_submission.md
      - Understanding the output: understanding_output.md
    - Module-specific information:
       - BGC detection: clusterrules.md
       - NRPS/PKS domains: modules/nrps_pks_domains.md
       - PKS type II: modules/t2pks.md
    - Local antiSMASH installation:
        - Installation: install.md
        - Starting command line runs: command_line.md
    - FAQ: faq.md
    - Glossary: glossary.md
    - About: about.md
theme: readthedocs
markdown_extensions:
    - footnotes
